# Generated by Django 3.2.11 on 2022-01-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=122, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.IntegerField()),
                ('prod_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('sweets', 'sweets'), ('choclates', 'choclates'), ('Junk Food', 'Junk Food')], default='sweets', max_length=10)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
