# Generated by Django 3.2.11 on 2022-01-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='email@gmail.com',
            field=models.EmailField(blank=True, max_length=122),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, default='Name Not Mentioned', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=123),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.TextField(blank=True, default='No desc', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(blank=True, default='PROD_NAME', max_length=100),
        ),
    ]
